In [1]:
#numpy-Array Manipulation

In [2]:
import numpy as np

In [3]:
ar=np.random.randint(1,10 ,(4,5))

In [4]:
ar

array([[6, 2, 4, 8, 1],
       [2, 2, 4, 4, 5],
       [7, 6, 5, 1, 5],
       [1, 1, 4, 2, 3]])

In [7]:
ar1=ar.reshape(10,2)

In [8]:
ar1

array([[6, 2],
       [4, 8],
       [1, 2],
       [2, 4],
       [4, 5],
       [7, 6],
       [5, 1],
       [5, 1],
       [1, 4],
       [2, 3]])

In [9]:
ar1.T

array([[6, 4, 1, 2, 4, 7, 5, 5, 1, 2],
       [2, 8, 2, 4, 5, 6, 1, 1, 4, 3]])

In [10]:
ar1.flatten()

array([6, 2, 4, 8, 1, 2, 2, 4, 4, 5, 7, 6, 5, 1, 5, 1, 1, 4, 2, 3])

In [12]:
ar2=np.array([1,2,3,4])

In [13]:
ar2

array([1, 2, 3, 4])

In [14]:
np.expand_dims(ar2 , axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [15]:
ar

array([[6, 2, 4, 8, 1],
       [2, 2, 4, 4, 5],
       [7, 6, 5, 1, 5],
       [1, 1, 4, 2, 3]])

In [19]:
np.expand_dims(ar , axis=0)

array([[[6, 2, 4, 8, 1],
        [2, 2, 4, 4, 5],
        [7, 6, 5, 1, 5],
        [1, 1, 4, 2, 3]]])

In [20]:
ar3=np.array([[1] ,[2] ,[3]])

In [21]:
ar3

array([[1],
       [2],
       [3]])

In [22]:
np.squeeze(ar3)

array([1, 2, 3])

In [1]:
import numpy as np

In [2]:
ar1

NameError: name 'ar1' is not defined

In [3]:
ar3=[1,2,3,4,5]

In [4]:
np.repeat(ar3 ,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5])

In [5]:
np.roll(ar3 ,2)

array([4, 5, 1, 2, 3])

In [6]:
np.diag(ar3)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [7]:
ar4=np.random.randint(1,10 ,(3,4))

In [8]:
ar5=np.random.randint(1,10 ,(3,4))

In [9]:
ar4

array([[3, 6, 4, 8],
       [4, 9, 6, 8],
       [1, 7, 9, 5]])

In [10]:
ar5

array([[9, 5, 2, 7],
       [6, 3, 3, 5],
       [8, 3, 3, 2]])

In [11]:
ar4+ar5

array([[12, 11,  6, 15],
       [10, 12,  9, 13],
       [ 9, 10, 12,  7]])

In [12]:
ar4*ar5

array([[27, 30,  8, 56],
       [24, 27, 18, 40],
       [ 8, 21, 27, 10]])

In [13]:
ar4%ar5

array([[3, 1, 0, 1],
       [4, 0, 0, 3],
       [1, 1, 0, 1]])

In [15]:
ar5%ar4

array([[0, 5, 2, 7],
       [2, 3, 3, 5],
       [0, 3, 3, 2]])

In [16]:
ar4>ar5

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [False,  True,  True,  True]])

In [17]:
#Numpy-string function 

In [18]:
ar6=np.array(['raju' , 'pratap'])

In [19]:
ar6

array(['raju', 'pratap'], dtype='<U6')

In [20]:
np.char.upper(ar6)

array(['RAJU', 'PRATAP'], dtype='<U6')

In [21]:
np.char.title(ar6)

array(['Raju', 'Pratap'], dtype='<U6')

In [22]:
#Numpy-Mathematical function

In [24]:
ar4

array([[3, 6, 4, 8],
       [4, 9, 6, 8],
       [1, 7, 9, 5]])

In [25]:
np.sin(ar4)

array([[ 0.14112001, -0.2794155 , -0.7568025 ,  0.98935825],
       [-0.7568025 ,  0.41211849, -0.2794155 ,  0.98935825],
       [ 0.84147098,  0.6569866 ,  0.41211849, -0.95892427]])

In [26]:
np.cos(ar4)

array([[-0.9899925 ,  0.96017029, -0.65364362, -0.14550003],
       [-0.65364362, -0.91113026,  0.96017029, -0.14550003],
       [ 0.54030231,  0.75390225, -0.91113026,  0.28366219]])

In [28]:
np.power(ar4 ,2)

array([[ 9, 36, 16, 64],
       [16, 81, 36, 64],
       [ 1, 49, 81, 25]])

In [29]:
np.mean(ar4)

5.833333333333333

In [31]:
np.median(ar4)

6.0